version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  json:
    (): pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s, %(filename)s, %(levelname)s, %(name)s, %(message)s'
    json_encoder: json.JSONEncoder
    rename_fields:
      message: 'log_message'


handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: json
    stream: ext://sys.stdout
  logfile:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: ./app/log/info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
loggers:
  sampleLogger:
    level: INFO
    handlers: [console,logfile]
    propagate: no
root:
  level: INFO
  handlers: [console,logfile]