# Single Stage Build
FROM python:3.9

WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt
COPY ./simple_webserver.py /app/simple_webserver.py

CMD ["python", "simple_webserver.py"]


